# qwer OS Netinstall & DE Selection
---
groupsUrl: local
required: true
label:
    sidebar: "DE & Mirrors"
    title: "Choose your Desktop Environment and Mirror"

# Options for users
groups:
  - name: "Desktop Environment"
    description: "Choose your preferred GUI"
    critical: true
    subgroups:
      - name: "KDE Plasma (Default)"
        description: "Modern and highly customizable KDE"
        packages:
          - kde-plasma/plasma-meta
          - kde-apps/kde-apps-meta
          - x11-base/xorg-server
        selected: true
      - name: "GNOME"
        description: "Simple and intuitive GNOME desktop"
        packages:
          - gnome-base/gnome
          - x11-base/xorg-server
        selected: false
      - name: "XFCE"
        description: "Lightweight and fast desktop environment"
        packages:
          - xfce-base/xfce4-meta
          - xfce-base/xfce4-extras
          - x11-base/xorg-server
        selected: false
  - name: "Gentoo Mirror"
    description: "Select the nearest mirror for faster downloads"
    subgroups:
      - name: "Global (Gentoo.org)"
        packages: [ "net-misc/gentoo-mirrors" ]
        selected: true
      - name: "South Korea (KAIST)"
        packages: [ "net-misc/gentoo-mirrors" ]
        selected: false
