# qwer OS Partitioning Configuration
---
# Partition layout options
efi:
    mountPoint:         "/boot/efi"
    recommendedSize:    512MiB
    minimumSize:        256MiB
    label:              "EFI"

# Default to "Use Entire Disk" with Manual Partitioning as an option
defaultFileSystemType:  "ext4"

# Use these flags for partition creation
requiredPartitionFlags: [ "boot", "esp" ]

# User-selectable options in Step 4
availableFreeSpaceThreshold: 10.0
availableFileSystemTypes:  ["ext4", "btrfs", "xfs"]

# Display options in Step 4
partitionOperations:
    - name: "erase"    # Step 4: Use entire disk
      selected: true
    - name: "manual"   # Step 4: Manual partition
      selected: false
