# OpenRC Service Management for qwer OS
---
# List of services to enable on the target system
services:
  - name: "dbus"
    action: "add"
    runlevel: "default"
  - name: "NetworkManager"
    action: "add"
    runlevel: "default"
  - name: "alsasound"
    action: "add"
    runlevel: "boot"
  - name: "udev"
    action: "add"
    runlevel: "sysinit"
  - name: "sddm"  # Default for KDE
    action: "add"
    runlevel: "default"
  - name: "chronyd"
    action: "add"
    runlevel: "default"
  - name: "ssh"
    action: "add"
    runlevel: "default"
