# Calamares settings for qwer OS
---
modules-search: [ local ]

instances:
- id:       qwer_os_install
  module:   install
  config:   install.conf

sequence:
- show:
    - locale          # Step 1: Language
    - welcome
- show:
    - netinstall      # Step 2: Mirror Selection (Mocked for Gentoo)
- show:
    - keyboard        # Step 3: Keyboard
- show:
    - partition       # Step 4: Partitioning
- show:
    - users
    - summary
- exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - networkcfg
    - hwclock
    - services-openrc  # Step 5: Installation & OpenRC
    - grubcfg
    - bootloader
    - displaymanager   # Set KDE/GNOME/XFCE
    - umount
- show:
    - finished

brand: qwer-os
branding: qwer-os
prompt-install: true
dont-chroot: false
